### ISSUE TITLE
Please add previews to README

### ISSUE THREAD

**Issue by AlekSi** [ashleymcnamara/gophers#1]
Probably part of README can be generated by small Go program.

**Comment by ashleymcnamara** [comment]
Good idea! On it! 

Ashley McNamara
Developer Evangelist | Rackspace
m:	(650) 533-9961
w:	www.rackspace.com  e: ashleymcnamara1@gmail.com

**Comment by egonelbre** [comment]
So you don't have to do the work:
1. Thumbnails: https://github.com/egonelbre/gophers/blob/master/update.go
2. Single collage: https://github.com/egonelbre/gophers/blob/025633974b3ae03997a5202ef1b4e2918622e320/collage.go

I move to thumbnails because then I won't have to update one big image, every time I make a small change in one image.

**Comment by egonelbre** [comment]
PS: the other reason for using thumbnails is to make sure that people can click on the thumbnail and open the large image.
